### ISSUE TITLE
exe 打开404

### ISSUE THREAD

**Issue by gnkhandsome** [lixk/easy-window#1]

**Comment by lixk** [comment]
启动参数需要指定页面地址

**Comment by sdqianfang** [comment]
> 启动参数需要指定页面地址

你好，必须通过脚本或命令行指定地址吗？

**Comment by lixk** [comment]
> > 启动参数需要指定页面地址
> 
> 你好，必须通过脚本或命令行指定地址吗？

也可以在其他程序里使用子程序运行，比如在python里
`subprocess.Popen('easy-window.exe -url index.html')` 
即可在窗体中呈现index.html页面
