### ISSUE TITLE
能不能加一个扩展，命令接口

### ISSUE THREAD

**Issue by Sun-ZhenXing** [lixk/easy-window#8]
类似于 shell(str:command, bool:hide/show)
如果没有这样的接口，程序不好扩展。
我觉得easy-window在写快速开发的程序上是很占优势的，但是Windows的基础功能应该有命令调用，我不知道这样好不好写。

**Comment by lixk** [comment]
> 类似于 shell(str:command, bool:hide/show)
> 如果没有这样的接口，程序不好扩展。
> 我觉得easy-window在写快速开发的程序上是很占优势的，但是Windows的基础功能应该有命令调用，我不知道这样好不好写。

加上了
